version: '2'

services:

  airbnbcollector:
    image: jenslaufer/airbnbcollector:3.4
    container_name: airbnbcollector
    depends_on:
      - postgresql
    volumes:       
      - ./configs:/collector/configs
    environment:
      USER: airbnb
    command: tail -f /dev/null

  postgresql:
    image: mdillon/postgis:10
    container_name: airbnbcollector-db
    restart: always
    volumes:  
      - ../postgresql/:/sql/
      - ./scripts:/docker-entrypoint-initdb.d/  
    environment:
      POSTGRES_PASSWORD: airbnb
      POSTGRES_USER: airbnb